server:
  port: "8080"

database:
  host: "postgres"
  port: "5432"
  user: "realstate"
  password: "realstate"
  dbname: "realstate_db"

kafka:
  brokers:
    - "localhost:9092"

apis:
  geocoding_api_key: "your-api-key-here"